export type TemplateLanguage = "python" | "sql" | "javascript";

export interface CodingReviewTemplateContent {
  id: string;
  language: TemplateLanguage;
  title: string;
  description: string;
  template_type: "blank" | "starter" | "dataset" | "dom";
  frontend_loader_key: string;
  code: string;
  sqlSchema?: string;
  domHtml?: string;
}

export const CODING_REVIEW_TEMPLATES: Record<string, CodingReviewTemplateContent> = {
  python_blank: {
    id: "py_blank",
    language: "python",
    title: "Blank Python",
    description: "Empty Python file.",
    template_type: "blank",
    frontend_loader_key: "python_blank",
    code: "# Write your code here\n",
  },
  python_data_analysis: {
    id: "py_data_analysis",
    language: "python",
    title: "Data Analysis Starter",
    description: "Starter with CSV load + basic stats.",
    template_type: "starter",
    frontend_loader_key: "python_data_analysis",
    code: [
      "import csv",
      "from statistics import mean",
      "",
      "# Sample data inline (replace with your own)",
      "rows = [",
      "    {\"name\": \"Ava\", \"score\": 88},",
      "    {\"name\": \"Noah\", \"score\": 92},",
      "    {\"name\": \"Mia\", \"score\": 79},",
      "]",
      "",
      "scores = [row[\"score\"] for row in rows]",
      "print(\"Average score:\", mean(scores))",
      "print(\"Top score:\", max(scores))",
    ].join("\n"),
  },
  python_web_scrape: {
    id: "py_web_scrape",
    language: "python",
    title: "Web Scraping Skeleton",
    description: "Requests + BeautifulSoup skeleton (no network in sandbox).",
    template_type: "starter",
    frontend_loader_key: "python_web_scrape",
    code: [
      "# Note: network calls are disabled in-browser.",
      "# Use this to practice parsing HTML with BeautifulSoup.",
      "",
      "from bs4 import BeautifulSoup",
      "",
      "html = \"\"\"",
      "<html>",
      "  <body>",
      "    <h1>Sample Page</h1>",
      "    <ul>",
      "      <li data-score='91'>Alpha</li>",
      "      <li data-score='87'>Beta</li>",
      "    </ul>",
      "  </body>",
      "</html>",
      "\"\"\"",
      "",
      "soup = BeautifulSoup(html, 'html.parser')",
      "items = soup.find_all('li')",
      "for item in items:",
      "    print(item.text, item[\"data-score\"])",
    ].join("\n"),
  },
  python_game_loop: {
    id: "py_game_loop",
    language: "python",
    title: "Game Loop Template",
    description: "Simple text-based game loop structure.",
    template_type: "starter",
    frontend_loader_key: "python_game_loop",
    code: [
      "player_hp = 10",
      "enemy_hp = 8",
      "",
      "while player_hp > 0 and enemy_hp > 0:",
      "    action = input('Attack or Defend? ').strip().lower()",
      "    if action == 'attack':",
      "        enemy_hp -= 2",
      "        print('You hit the enemy. Enemy HP:', enemy_hp)",
      "    else:",
      "        player_hp -= 1",
      "        print('You defend. Player HP:', player_hp)",
      "",
      "if player_hp > 0:",
      "    print('You win!')",
      "else:",
      "    print('Game over.')",
    ].join("\n"),
  },
  python_api_request: {
    id: "py_api_request",
    language: "python",
    title: "API Request Template",
    description: "Fetch data from a sample endpoint.",
    template_type: "starter",
    frontend_loader_key: "python_api_request",
    code: [
      "# Network requests are disabled in-browser.",
      "# Simulate API responses with local data.",
      "",
      "data = {",
      "    'status': 'ok',",
      "    'items': [",
      "        {'id': 1, 'name': 'Atlas'},",
      "        {'id': 2, 'name': 'Nova'},",
      "    ]",
      "}",
      "",
      "for item in data['items']:",
      "    print(item['id'], item['name'])",
    ].join("\n"),
  },
  sql_blank: {
    id: "sql_blank",
    language: "sql",
    title: "Blank SQL",
    description: "Empty SQL editor.",
    template_type: "blank",
    frontend_loader_key: "sql_blank",
    code: "-- Write SQL here\n",
  },
  sql_university_db: {
    id: "sql_university_db",
    language: "sql",
    title: "University Database",
    description: "Students, courses, enrollments, grades.",
    template_type: "dataset",
    frontend_loader_key: "sql_university_db",
    code: "SELECT * FROM students;",
    sqlSchema: [
      "CREATE TABLE students (id INTEGER PRIMARY KEY, name TEXT, major TEXT, gpa REAL);",
      "CREATE TABLE courses (id INTEGER PRIMARY KEY, name TEXT, department TEXT);",
      "CREATE TABLE enrollments (student_id INTEGER, course_id INTEGER, grade TEXT);",
      "INSERT INTO students VALUES (1, 'Ava', 'Biology', 3.7);",
      "INSERT INTO students VALUES (2, 'Noah', 'Computer Science', 3.9);",
      "INSERT INTO students VALUES (3, 'Mia', 'History', 3.2);",
      "INSERT INTO courses VALUES (10, 'Genetics', 'Biology');",
      "INSERT INTO courses VALUES (11, 'Algorithms', 'Computer Science');",
      "INSERT INTO courses VALUES (12, 'Modern History', 'History');",
      "INSERT INTO enrollments VALUES (1, 10, 'A');",
      "INSERT INTO enrollments VALUES (2, 11, 'A-');",
      "INSERT INTO enrollments VALUES (3, 12, 'B+');",
    ].join("\n"),
  },
  sql_ecommerce_db: {
    id: "sql_ecommerce_db",
    language: "sql",
    title: "E-commerce Database",
    description: "Products, orders, customers.",
    template_type: "dataset",
    frontend_loader_key: "sql_ecommerce_db",
    code: "SELECT * FROM customers;",
    sqlSchema: [
      "CREATE TABLE customers (id INTEGER PRIMARY KEY, name TEXT, city TEXT);",
      "CREATE TABLE products (id INTEGER PRIMARY KEY, name TEXT, price REAL);",
      "CREATE TABLE orders (id INTEGER PRIMARY KEY, customer_id INTEGER, product_id INTEGER, quantity INTEGER);",
      "INSERT INTO customers VALUES (1, 'Liam', 'Atlanta');",
      "INSERT INTO customers VALUES (2, 'Emma', 'Chicago');",
      "INSERT INTO products VALUES (10, 'Notebook', 4.99);",
      "INSERT INTO products VALUES (11, 'Pen Set', 9.49);",
      "INSERT INTO orders VALUES (100, 1, 10, 3);",
      "INSERT INTO orders VALUES (101, 2, 11, 1);",
    ].join("\n"),
  },
  sql_music_db: {
    id: "sql_music_db",
    language: "sql",
    title: "Music Library Database",
    description: "Artists, albums, tracks.",
    template_type: "dataset",
    frontend_loader_key: "sql_music_db",
    code: "SELECT * FROM artists;",
    sqlSchema: [
      "CREATE TABLE artists (id INTEGER PRIMARY KEY, name TEXT, genre TEXT);",
      "CREATE TABLE albums (id INTEGER PRIMARY KEY, artist_id INTEGER, title TEXT, year INTEGER);",
      "CREATE TABLE tracks (id INTEGER PRIMARY KEY, album_id INTEGER, title TEXT, length_seconds INTEGER);",
      "INSERT INTO artists VALUES (1, 'Aurora Lane', 'Indie');",
      "INSERT INTO artists VALUES (2, 'Cedar Wave', 'Electronic');",
      "INSERT INTO albums VALUES (10, 1, 'Northern Lights', 2022);",
      "INSERT INTO albums VALUES (11, 2, 'Neon Drift', 2023);",
      "INSERT INTO tracks VALUES (100, 10, 'Starlight', 210);",
      "INSERT INTO tracks VALUES (101, 11, 'Pulse', 198);",
    ].join("\n"),
  },
  js_blank: {
    id: "js_blank",
    language: "javascript",
    title: "Blank JavaScript",
    description: "Empty JS file.",
    template_type: "blank",
    frontend_loader_key: "js_blank",
    code: "// Write your code here\n",
  },
  js_dom_starter: {
    id: "js_dom_starter",
    language: "javascript",
    title: "DOM Starter",
    description: "Basic HTML + DOM hooks.",
    template_type: "dom",
    frontend_loader_key: "js_dom_starter",
    code: [
      "const title = document.getElementById('title');",
      "const button = document.getElementById('btn');",
      "",
      "button.addEventListener('click', () => {",
      "  title.textContent = 'You clicked the button.';",
      "});",
    ].join("\n"),
    domHtml: [
      "<div style=\"font-family: sans-serif; padding: 12px;\">",
      "  <h2 id=\"title\">DOM Starter</h2>",
      "  <button id=\"btn\">Click me</button>",
      "</div>",
    ].join("\n"),
  },
  js_fetch_starter: {
    id: "js_fetch_starter",
    language: "javascript",
    title: "Fetch API Starter",
    description: "Fetch + render JSON.",
    template_type: "starter",
    frontend_loader_key: "js_fetch_starter",
    code: [
      "const sample = { items: ['Atlas', 'Nova', 'Sol'] };",
      "console.log('Items:', sample.items.join(', '));",
    ].join("\n"),
  },
  js_array_playground: {
    id: "js_array_playground",
    language: "javascript",
    title: "Array Playground",
    description: "Preloaded array data to manipulate.",
    template_type: "starter",
    frontend_loader_key: "js_array_playground",
    code: [
      "const numbers = [3, 12, 7, 19, 4, 8];",
      "const overTen = numbers.filter((n) => n > 10);",
      "console.log('Over 10:', overTen);",
    ].join("\n"),
  },
};

export function getTemplateByKey(key: string) {
  return CODING_REVIEW_TEMPLATES[key] || null;
}
